version: '3'

services:

  web1:
    container_name: docker-ubuntu-18.04-web1
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'bash'
    restart: always
    ports:
      - 1618:80
      - 1619:8888
    volumes:
      - ./webroot:/srv/www/test
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
